# DB Config details
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_tenancy_db
    driverClassName: org.postgresql.Driver
    username: dev_tenancy_db_user
    password: dev_tenancy_db_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect